BEGIN;
CREATE TABLE IF NOT EXISTS pgmigration (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  scriptname VARCHAR(100),
  dateapplied TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'UTC')
);
END;